spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 182d64b36e561edddbdd
            client-secret: 0e13e460986b6925d55a6da5a7c325286f7cb9ed
            scope:
              - read:user
              - notifications
            redirect-uri: 'http://localhost:9090/login/oauth2/code/github'
github:
  base:
    url: https://api.github.com/

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

server:
  port: 9090